services:
  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./apps/web:/app
      - /app/node_modules

  software:
    build:
      context: .
      dockerfile: apps/software/Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./apps/software:/app
      - /app/node_modules