version: '3.8'

services:
  nextjs-site:
    build:
      context: .
      dockerfile: apps/nextjs-site/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./apps/nextjs-site:/app
      - /app/node_modules

  react-vite-app:
    build:
      context: .
      dockerfile: apps/react-vite-app/Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./apps/react-vite-app:/app
      - /app/node_modules