---
- name: Générer le fichier .env pour Email
  template:
    src: templates/email.env.j2
    dest: "{{ email_path }}/.env"
    mode: "0600"
  tags: [email, env]

- name: Générer le fichier .env pour Email package
  template:
    src: templates/email-package.env.j2
    dest: "{{ email_package_path }}/.env"
    mode: "0600"
  tags: [email, env]

- name: Déployer le worker email
  community.docker.docker_compose:
    project_src: "{{ email_path }}"
    state: present
    build: true
    restarted: true
  tags: [email, deploy]