- name: reload nginx
  service:
    name: nginx
    state: reloaded
  when: ansible_env.ACT is not defined

- name: restart nginx
  service:
    name: nginx
    state: restarted
  when: ansible_env.ACT is not defined
