- name: Install Docker
  apt:
    name: docker.io
    state: present

- name: Install Kubernetes tools (kubeadm, kubelet, kubectl)
  apt:
    name:
      - kubeadm
      - kubelet
      - kubectl
    state: present

- name: Initialize Kubernetes master
  command: kubeadm init --pod-network-cidr=10.244.0.0/16
  when: inventory_hostname == "master-node"

- name: Join worker nodes to the cluster
  command: "kubeadm join {{ master_ip }}:6443 --token {{ token }} --discovery-token-ca-cert-hash sha256:{{ ca_cert_hash }}"
  when: inventory_hostname != "master-node"
