apiVersion: apps/v1
kind: Deployment
metadata:
  name: software
  namespace: saas-apps
spec:
  replicas: 2
  selector:
    matchLabels:
      app: software
  template:
    metadata:
      labels:
        app: software
    spec:
      containers:
        - name: software
          image: your-dockerhub-username/software:latest
          ports:
            - containerPort: 3001
