apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-vite-app
  namespace: saas-apps
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-vite-app
  template:
    metadata:
      labels:
        app: react-vite-app
    spec:
      containers:
        - name: react-vite-app
          image: your-dockerhub-username/react-vite-app:latest
          ports:
            - containerPort: 3001
