apiVersion: v1
kind: Service
metadata:
  name: software
  namespace: saas-apps
spec:
  selector:
    app: software
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
  type: LoadBalancer
