apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: saas-apps
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: your-dockerhub-username/web:latest
          ports:
            - containerPort: 3000
