---
- name: Générer le fichier .env pour le global
  template:
    src: templates/global.env.j2
    dest: "{{ global_path }}/.env"
    mode: "0600"
  tags: [global, env]

- name: Déployer le compose global
  community.docker.docker_compose:
    project_src: "{{ global_path }}"
    state: present
    build: true
    restarted: true
  tags: [global, deploy]