- name: Mettre à jour les paquets
  apt: update_cache=yes

- name: Installer UFW
  apt: name=ufw

- block:
    - name: Ouvrir port SSH personnalisé
      ufw:
        rule: allow
        port: "{{ vault_ssh_port }}"
        proto: tcp

    - name: Appliquer les règles métier
      ufw:
        rule: "{{ item.rule | default('allow') }}"
        port: "{{ item.port }}"
        proto: "{{ item.proto | default('tcp') }}"
      loop: "{{ vault_ufw_rules }}"

    - name: Activer UFW
      ufw: state=enabled

  rescue:
    - name: Rollback en cas d'erreur
      ufw: state=disabled
      ignore_errors: yes

    - name: Alerter l'équipe
      slack:
        token: "{{ vault_slack_token }}"
        msg: "Échec de configuration UFW sur {{ inventory_hostname }}"