# Étape Base
FROM oven/bun:latest
WORKDIR /usr/src/app

# Copy package.json and install dependencies
COPY package.json bun.lock turbo.json ./
COPY apps/software/package.json ./apps/software/package.json
COPY packages/ ./packages/

# Install dependencies
RUN bun init
RUN bun install

# Copy the rest of the application code
COPY . .

# Expose the development server port
EXPOSE 3000

# Run the development server for the software app
CMD ["bun", "run", "--filter", "software", "dev"]

# // Commandes
# # Créer l'image Docker
# docker build -t bastiencdr/software.dev:latest -f apps/software/Dockerfile.dev .
# # Lancer le conteneur Docker
# docker run -p 3000:3000 -v $(pwd):/usr/src/app bastiencdr/software.dev:latest