# Étape 1 : Base
FROM oven/bun:1 AS base
WORKDIR /usr/src/app

# Étape 2 : Installation des dépendances
FROM base AS install
RUN mkdir -p /temp/dev
COPY package.json bun.lock turbo.json /temp/dev/
COPY apps/software/package.json /temp/dev/apps/software/package.json
COPY packages/ /temp/dev/packages/
RUN cd /temp/dev && bun install

# Étape 3 : Copier le code source et les dépendances
FROM base AS final
COPY --from=install /temp/dev/node_modules ./node_modules
COPY --from=install /temp/dev/apps/software ./apps/software
COPY --from=install /temp/dev/packages ./packages

RUN bun init

# Étape 4 : Exécution en mode développement
EXPOSE 3000
CMD ["bun","run", "dev"]