---
- name: Construire l'image Docker
  docker_image:
    name: "{{ docker_image_name }}"
    build:
      path: ../
      dockerfile: apps/web/Dockerfile
      args:
        HELLO_WORLD: "{{ hello_world_arg }}"
    source: build

- name: Démarrer le conteneur Docker
  docker_container:
    name: "{{ docker_container_name }}"
    image: "{{ docker_image_name }}"
    state: started
    ports:
      - "{{ docker_port }}:3000"
    restart_policy: always

- name: Vérifier que le conteneur est en cours d'exécution
  docker_container_info:
    name: "web_app"
  register: container_info

- name: Afficher l'état du conteneur
  debug:
    var: container_info.container.State.Status