- name: Ensure namespace exists
  k8s:
    api_version: v1
    kind: Namespace
    name: saas-apps
    state: present

- name: Deploy Next.js application
  k8s:
    state: present
    definition: "{{ lookup('file', 'k8s/nextjs-deployment.yaml') }}"

- name: Deploy React Vite application
  k8s:
    state: present
    definition: "{{ lookup('file', 'k8s/react-vite-deployment.yaml') }}"

- name: Expose Next.js service
  k8s:
    state: present
    definition: "{{ lookup('file', 'k8s/nextjs-service.yaml') }}"

- name: Expose React Vite service
  k8s:
    state: present
    definition: "{{ lookup('file', 'k8s/react-vite-service.yaml') }}"
