- name: Supprimer les anciens conteneurs
  docker_container:
    name: "{{ item.container }}"
    state: absent
    container_default_behavior: compatibility
  loop: "{{ apps }}"

- name: Construire les images Docker (sauf pour les images officielles)
  docker_image:
    name: "{{ item.image }}"
    build:
      path: ../
      dockerfile: "{{ item.dockerfile }}"
      args:
        HELLO_WORLD: "{{ hello_world_arg }}"
      pull: yes
    source: build
  when: item.dockerfile != ""
  loop: "{{ apps }}"

- name: Démarrer les conteneurs
  docker_container:
    name: "{{ item.container }}"
    image: "{{ item.image }}"
    state: started
    recreate: yes
    ports:
      - "{{ item.port }}:{{ item.internal_port }}"
    restart_policy: always
    container_default_behavior: compatibility
  loop: "{{ apps }}"

- name: Vérifier que les conteneurs sont en cours d'exécution
  docker_container_info:
    name: "{{ item.container }}"
  register: container_info
  loop: "{{ apps }}"

- name: Afficher l'état des conteneurs
  debug:
    msg: "{{ item.item.name }} → {{ item.container.State.Status }}"
  loop: "{{ container_info.results }}"
