- name: Installer Nginx
  apt:
    name: nginx
    state: latest
  when: ansible_env.ACT is not defined

- name: Créer les dossiers Nginx nécessaires
  file:
    path: "/etc/nginx/sites-available"
    state: directory
    mode: "0755"

- name: Créer les liens Nginx nécessaires
  file:
    path: "/etc/nginx/sites-enabled"
    state: directory
    mode: "0755"

- name: Configurer les sites Nginx pour chaque app
  template:
    src: templates/nginx-app.conf.j2
    dest: "/etc/nginx/sites-available/{{ item.domain_name }}.conf"
  notify: reload nginx
  loop: "{{ apps }}"

- name: Activer les sites
  file:
    src: "/etc/nginx/sites-available/{{ item.domain_name }}.conf"
    dest: "/etc/nginx/sites-enabled/{{ item.domain_name }}.conf"
    state: link
    force: yes
  loop: "{{ apps }}"

- name: Supprimer le site par défaut
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Vérifier la configuration Nginx
  command: nginx -t
  register: nginx_test
  changed_when: false
  when: ansible_env.ACT is not defined
  notify: restart nginx

- name: Redémarrer Nginx si configuration valide
  service:
    name: nginx
    state: restarted
  when: (nginx_test.rc | default(1)) == 0 and (ansible_env.ACT is not defined)
