---
      
- name: Déployer l'application sur les hôtes maîtres
  hosts: docker_master
  connection: local
  become: yes
  vars_files:
    - vars/defaults.yml
  roles:
    - { role: docker, tags: [docker] }
    - { role: app-deploy, tags: [app-deploy] }
    - { role: nginx, tags: [nginx] }
    - { role: certbot, tags: [certbot] }