---
- name: Configurer Docker sur les hôtes maîtres
  hosts: docker_master
  connection: local
  become: yes 
  vars_files:
    - vars/defaults.yml
    - vars/secrets.yml
  roles:
    - role: docker-setup
      tags: docker-setup


# - name: Configurer le firewall
#   hosts: docker_master
#   connection: ssh
#   become: yes
#   vars_files:
#     - vars/defaults.yml
#     - vars/secrets.yml
#   roles:
#     - role: firewall
#       tags: firewall
      
- name: Déployer l'application sur les hôtes maîtres
  hosts: docker_master
  connection: local
  become: yes 
  vars_files:
    - vars/defaults.yml
    - vars/secrets.yml
  roles:
    - role: app-deploy
      tags: app-deploy

- name: Configurer nginx
  hosts: docker_master
  connection: local
  become: yes
  vars_files:
    - vars/defaults.yml
    - vars/secrets.yml
  roles:
    - role: nginx-config
      tags: nginx-config

- name: Configurer certbot
  hosts: docker_master
  connection: local
  become: yes
  vars_files:
    - vars/defaults.yml
    - vars/secrets.yml
  roles:
    - role: certbot
      tags: certbot

