---
apps:
  - name: web
    image: web:latest
    container: web
    dockerfile: apps/web/Dockerfile
    port: 3011
    internal_port: 3000

  - name: postgres
    image: postgres:16-alpine
    container: postgres
    dockerfile: ""
    port: 5432
    internal_port: 5432