- name: Vérifier que l'email Let's Encrypt est défini
  assert:
    that:
      - letsencrypt_email is defined
      - letsencrypt_email | length > 3
    fail_msg: "⚠️ La variable 'letsencrypt_email' est obligatoire."

- name: Créer le dossier pour les challenges Certbot
  file:
    path: /var/www/certbot
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'
  become: true

- name: Lancer Certbot pour chaque domaine (réel ou mock)
  include_tasks: certbot_per_domain.yml
  loop: "{{ apps }}"
  loop_control:
    loop_var: app
