---
- name: Vérifier que l'e-mail Let’s Encrypt est défini
  assert:
    that:
      - letsencrypt_email is defined
      - letsencrypt_email | length > 3
    fail_msg: "⚠️ Variable letsencrypt_email est manquante ou invalide."

- name: Installer Certbot et le plugin Nginx
  package:
    name:
      - certbot
      - python3-certbot-nginx
    state: present

- name: Vérifier l'installation de certbot
  command: certbot --version
  register: certbot_version
  changed_when: false

- name: Afficher la version installée
  debug:
    msg: "Certbot {{ certbot_version.stdout }} installé avec succès"