---
- name: Activer le dépôt Universe
  apt_repository:
    repo: "deb http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release }} universe"
    state: present
  tags: certbot

- name: Mettre à jour le cache APT
  apt:
    update_cache: yes
  tags: certbot

- name: Installer les paquets Certbot
  apt:
    name:
      - certbot
      - python3-certbot-nginx
    state: latest
  tags: certbot

- name: Exécuter Certbot
  command: >
    certbot --nginx -d {{ domain_name }}
    --non-interactive
    --agree-tos
    -m {{ certbot_email }}
    --redirect
    --keep-until-expiring
  register: certbot_result
  changed_when: "'No certificates were received' not in certbot_result.stdout"
  tags: certbot