name: Deploy Application with Ansible

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: Run Ansible Playbook
        run: |
           ansible-playbook -i ./ansible/inventory.ini ./ansible/playbook-deploy.yml --vault-password-file ./ansible/vault_pass.txt